# Generated by Django 5.2.7 on 2025-10-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_post_like_post_id_rename_user_like_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
