# Generated by Django 5.2.7 on 2025-10-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_post_id_like_post_rename_user_id_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
