# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_author_post_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
